
server:
  port: 8080
  debug: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/productdb
    username: root
    password: password
#    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
#    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
#      show-sql: true
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}



