
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/paymentdb
    username: root
    password: password

  #    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    #    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296